spring.application.name=delivery-service
spring.config.import=configserver:http://${CONFIG_SERVER_HOST:localhost}:8888
spring.cloud.config.username=${CONFIG_SERVER_USER}
spring.cloud.config.password=${CONFIG_SERVER_PASSWORD}
